version: '3.7'

volumes:
  store:
  node_modules:
  gem_cache:

services:
  web:
    image: devtalk_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - gem_cache:/gems
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    command: ./bin/rails s -b '0.0.0.0' -p 3000
    depends_on:
      - db
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - store:/var/lib/postgresql/data
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devtalk_development